fieldtrial/urls.py
from django.urls import path
from django.urls import re_path

from . import views

urlpatterns = [
    # ex: /fieldtrial/ placeholder with html template loading
    path('', views.index_loading, name='index'),

    # display all field trials
    path('all', views.index, name='index_real'),

    # single study/study_id
    path('study/<study_id>', views.single_study),

    # single study's plots plots/study_id
    path('plots/<plot_id>', views.single_plot),

    # get one field trial json
    path('ajax/get_fieldtrial/', views.search_fieldtrial),

    # get one field trial page /fieldtrial/fieldtrial_id
    re_path(r'(?P<fieldtrial_id>[A-z0-9-\w%]+)$', views.single_fieldtrial)


]

filedownload/urls.py
# Import path module
from django.urls import path
from django.urls import re_path
# Import views
from filedownload import views

# Set path for download
app_name = 'download'
urlpatterns = [
    #path('', views.index, name='index'),
    #path('', views.download_file, name='download'),
    path('<filename>', views.download_CSV, name='download'),
]

grassroots_services_django_web/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('service/', include('service.urls')),
    path('fieldtrial/', include('fieldtrial.urls')),
    path('download/', include('filedownload.urls', namespace='downloads')),
     path('photo_receiver/', include('photo_receiver.urls')),
    # path('admin/', admin.site.urls),
]

service/urls.py
from django.urls import path
from django.urls import re_path

from . import views

urlpatterns = [
    # ex: /service/
    path('', views.index, name='index'),

    # get all services json
    path('ajax/get_all_services/', views.index_ajax),

    # get one service json
    path('ajax/get_one_service/', views.single_service_ajax),

    # for all other backend post request
    path('ajax/interact_backend/', views.interact_with_apache),

    path('private/', views.private_index),
    path('private/ajax/get_all_services/', views.private_index_ajax),
    path('private/ajax/get_one_service/', views.private_single_service_ajax),
    path('private/ajax/interact_backend/', views.private_interact_with_apache),
    re_path(r'private/(?P<service_alt_name>[A-z0-9-\w%]+)$', views.private_single_service),

    path('queen/', views.queen_index),
    path('queen/ajax/get_all_services/', views.queen_index_ajax),
    path('queen/ajax/get_one_service/', views.queen_single_service_ajax),
    path('queen/ajax/interact_backend/', views.queen_interact_with_apache),
    re_path(r'queen/(?P<service_alt_name>[A-z0-9-\w%]+)$', views.queen_single_service),


    # for copo ontology lookup services
    path('api/co_ols', views.crop_ontology_search),

    # for grassroots search services result with payload
    path('payload/<payload>', views.single_service_with_payload),

    # for grassroots search query in url
    # e.g. https://grassroots.tools/service/search/paragon
    path('search/<search_q>', views.single_service_search_q),

    # service name e.g. /service/blast-blastn
    re_path(r'(?P<service_alt_name>[A-z0-9-\w%]+)$', views.single_service),
]

fieldtrial/views.py
from django.shortcuts import render
import json
import os

from django.conf import settings
import numpy as np

from django import template
from plotly.offline import plot
from plotly.graph_objs import Scatter
from urllib.parse import urljoin

register = template.Library()


# Create your views here.

from django.http import HttpResponse
from .grassroots_fieldtrial_requests import get_all_fieldtrials
from .grassroots_fieldtrial_requests import get_fieldtrial
from .grassroots_fieldtrial_requests import get_study
from .grassroots_fieldtrial_requests import get_plot
from .grassroots_fieldtrial_requests import search_fieldtrial

from .grassroots_plots import numpy_data
from .grassroots_plots import plotly_plot
from .grassroots_plots import seaborn_plot
from .grassroots_plots import treatments
from .grassroots_plots import dict_phenotypes
from .grassroots_plots import observation_dates

from .grassroots_csv import create_CSV

# path to the local directory where the images are stored. Currently in the apache directory
local_base_path = settings.MEDIA_ROOT  
# url to access the images from the web. grassroots.tools/media or grassroots.tools/beta/media
web_base_url = settings.PHOTO_URL_SERVER.rstrip('/') + '/' + settings.MEDIA_URL.lstrip('/') 

'''
Field trial index page request, pre-load the template
'''
def index_loading(request):
    #return render(request, 'fieldtrial_loading.html', {})
    return render(request, 'fieldtrial/loading.html', {})

'''
Field trial index page request, with all field trials
'''
def index(request):
    #return render(request, 'fieldtrial.html', {'data': get_all_fieldtrials, 'type': 'AllFieldTrials'})
    return render(request, 'fieldtrial/fieldtrial.html', {'data': get_all_fieldtrials, 'type': 'AllFieldTrials'})

'''
One Field trial page request
'''
def single_fieldtrial(request, fieldtrial_id):
    #return render(request, 'fieldtrial.html', {'data': get_fieldtrial(fieldtrial_id), 'type': 'Grassroots:FieldTrial'})
    return render(request, 'fieldtrial/fieldtrial.html', {'data': get_fieldtrial(fieldtrial_id), 'type': 'Grassroots:FieldTrial'})

'''
One study page request
'''
def single_study(request, study_id):
   # base_url="https://grassroots.tools"
    base_url=settings.BASE_URL
    
    print (settings)
    study = get_study(study_id)
    result_json = json.loads (study)
    study_json = result_json ['results'][0]['results'][0]['data']
    
    if  "phenotypes" in study_json: 
        phenotypes = result_json['results'][0]['results'][0]['data']['phenotypes']  # for CSV file
    if  'plots' in study_json: 
        plot_array = result_json['results'][0]['results'][0]['data']['plots']       # for CSV 
    if  'treatment_factors' in study_json:
        treatment_factors = result_json['results'][0]['results'][0]['data']['treatment_factors'] # for CSV

    full_path=request.build_absolute_uri()
    
    ft_id         = study_json['parent_field_trial']['_id']['$oid']
    individual_id = study_json['_id']['$oid']
    
    N_t=0
    counters=[]
    flag=False
    ## number of treatment factors
    if  study_json['treatment_factors']:
        #print(len(study_json['treatment_factors']))
        N_t = len(study_json['treatment_factors'])
        value1 = study_json['treatment_factors']
    
        #values per treatment. create array for nested for loop 
        for i in range(N_t):
            ranges=range(len(value1[i]['values']))
            counters.append (ranges)
            flag=True
   
    ## create CSV file /filedownload/Files for link grassroots.tools/download/ID 
    if  "phenotypes" in study_json: 
        create_CSV(plot_array, phenotypes, treatment_factors, study_id)

    ### replace 'study' for 'plots' to create the link to the plots in given study ###
    full_path_plots=full_path.replace('study', 'plots')
    print ("full path plots 1: ", full_path_plots)

    full_path_plots=full_path_plots.replace("http://127.0.0.1:8000", base_url)
    print ("full path plots 2: ", full_path_plots)
    
    ### link for field trial name replace indiviual id for id of the field trial ###
    field_trial_link=full_path.replace('study/', '')
    field_trial_link=field_trial_link.replace(individual_id, ft_id)
    field_trial_link=field_trial_link.replace("http://127.0.0.1:8000", base_url)

    ## FIND IMAGES FOR CAROUSEL 
    ##local_base_path = "/home/daniel/Applications/apache/htdocs/TEST"
    #web_base_url="https://grassroots.tools/newbeta/media"
    
    imageUrls = []

    for plot in plot_array:
        if plot.get('rows') and plot['rows'][0].get('study_index'):
            study_index = plot['rows'][0]['study_index']  # Extract study_index from the first row
            #print(study_index)
            plot_dir = f"{local_base_path}{study_id}/plot_{study_index}"
            web_plot_dir = f"{web_base_url}{study_id}/plot_{study_index}"            
            plot_images = list_image_files(web_plot_dir, plot_dir)
            imageUrls.extend(plot_images)
    
    #imageUrls = [
    #    'http://127.0.0.1:2000/TEST/64b6449ad6500621c01c65e2/plot_1/photo_plot_1_2024_02_09.jpg',
    #    'http://127.0.0.1:2000/TEST/64b6449ad6500621c01c65e2/plot_2/photo_plot_2_2024_02_14.jpg'
    #]
    #imageUrls = [
    #    'https://grassroots.tools/beta/field_trial_data/APItest/64f1e4e77c486e019b4e3017/photo_plot_1_2024_02_09.jpg',
    #    'https://grassroots.tools/beta/field_trial_data/APItest/64f1e4e77c486e019b4e3017/photo_plot_1_2024_02_13.jpg',
    #    'https://grassroots.tools/beta/field_trial_data/APItest/64f1e4e77c486e019b4e3017/photo_plot_2_2024_02_09.jpg',
    #]
    ##imageUrls = []
	
    print ("full path plots 3: ", full_path_plots)
    print ("base_url: ", base_url)

    #return render(request, 'study.html', {'data': study, 'study_json': study_json, 'type': 'Grassroots:Study', 'path_plots':full_path_plots, 'ft_path':field_trial_link, 'N_treatments':range(N_t), 'counters':counters, 'flag':flag} )
    return render(request, 'fieldtrial/study.html', {'data': study, 
                                                     'study_json': study_json, 
                                                     'type': 'Grassroots:Study', 
                                                     'path_plots':full_path_plots, 
                                                     'ft_path':field_trial_link, 
                                                     'N_treatments':range(N_t), 
                                                     'counters':counters, 
                                                     'flag':flag, 
                                                     'imageUrls':imageUrls } )
def list_image_files(base_url, directory_path):
    """
    Generate web-accessible URLs for image files in a specified directory.
    """
    image_files = []
    supported_extensions = ['.jpg', '.jpeg', '.png']
    try:
        # List all files in the directory
        for item in os.listdir(directory_path):
            # Check if the file is an image
            if any(item.endswith(ext) for ext in supported_extensions):
                # Construct web-accessible URL
                image_url = f"{base_url}/{item}"
                image_files.append(image_url)
    except FileNotFoundError:
        print("Directory not found:", directory_path)

    return image_files

    
'''
One study's plots page request
'''
def single_plot(request, plot_id):
    plot = get_plot(plot_id)
    plot_json = json.loads(plot)
    study_name = plot_json['results'][0]['results'][0]['data']['so:name']
    study_data = plot_json ['results'][0]['results'][0]['data']

    plot_array = plot_json['results'][0]['results'][0]['data']['plots']     
    treatment_factors = plot_json['results'][0]['results'][0]['data']['treatment_factors']

    total_rows    = plot_json['results'][0]['results'][0]['data']['num_rows']
    total_columns = plot_json['results'][0]['results'][0]['data']['num_columns']


    if  'phenotypes' in study_data:
        phenotypes = plot_json['results'][0]['results'][0]['data']['phenotypes']  #
        dictTraits = dict_phenotypes(phenotypes, plot_array)  # dictionary to fill dropdown menu
        default_name = list(dictTraits.keys())[0]             # select first phenotype as default
    else:
        dictTraits = {'No Data':'No data'}  #
        phenotypes = {'No Data': 'No Data'}
        default_name = list(dictTraits.keys())[0]       

   
    print("Default phenotype: ", default_name )

    if 'singlePhenotype' in request.GET:
        selected_phenotype = request.GET['singlePhenotype']
    else:
        selected_phenotype = default_name

    matrices   = numpy_data(plot_array, phenotypes, selected_phenotype, total_rows, total_columns)

    row     = matrices[0]
    column  = matrices[1]
    row_raw = matrices[2]
    row_acc = matrices[3]
    traitName = matrices[4]
    units     = matrices[5]
    plotID    = matrices[6]

    plotIDs      =  plotID.reshape(row,column)
    accession    = row_acc.reshape(row,column)
    #plotlyMatrix = row_raw.reshape(row,column) #reshape in plotly_div()
    static    = row_raw.reshape(row,column)
    
    treatment=[]
    if ( len(treatment_factors)>0):
          treatment = treatments(plot_array, row, column)

     # Generate the observation dates matrix
    dates = observation_dates(plot_array, row, column, selected_phenotype)
    #print ("dates__________", dates)
    # Check if all dates are "N/A"
    if np.all(dates == "N/A"):
        dates = []  # Empty list if all dates are "N/A"

    create_CSV(plot_array, phenotypes, treatment_factors, plot_id)
    plot_div = plotly_plot(row_raw, accession, traitName, units, plotIDs, treatment, dates)
    
    data = plot
    imageUrls = []
    ## FIND IMAGES FOR CAROUSEL 
    #####local_base_path = "/home/daniel/Applications/apache/htdocs/TEST"
    ##web_base_url="https://grassroots.tools/newbeta/media"
    for plot in plot_array:
        if plot.get('rows') and plot['rows'][0].get('study_index'):

fieldtrial/templates/fieldtrial/loading.html
{% extends 'base.html' %}
{% load static %}

{% block all_styles_and_scripts %}
{{ block.super }} 
<script type="text/javascript"
        src="{% static 'scripts/jquery/jqrangeslider/jQAllRangeSliders-withRuler-min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'scripts/jquery/jqrangeslider/css/iThing.css' %}"
      type="text/css"/>

    <!-- ********************************************************-->
    <!-- Leaflet NEWEST VERSION -->
    <link rel="stylesheet" href="{% static 'fieldtrial/SCRIPTS/leaflet/leaflet.css' %}"/>
    <script src="{% static 'fieldtrial/SCRIPTS/leaflet/leaflet.js' %}"></script> 

    <!-- Leaflet markercluster NEWEST VERSION -->
    <link rel="stylesheet" href="{% static 'fieldtrial/SCRIPTS/leaflet.markercluster/MarkerCluster.css' %}"/>
    <link rel="stylesheet" href="{% static 'fieldtrial/SCRIPTS/leaflet.markercluster/MarkerCluster.Default.css' %}"/>
    <script src="{% static 'fieldtrial/SCRIPTS/leaflet.markercluster/leaflet.markercluster.js' %}"></script>
<style type="text/css">
    .modal-dialog {
    max-width: 70%;
    }
    .modal-body {
        height: 250px;
        overflow-y: auto;
    }

    @media (min-height: 500px) {
        .modal-body {
            height: 400px;
        }
    }

    @media (min-height: 800px) {
        .modal-body {
            height: 600px;
        }
    }

    #resultTable td, th {
        text-align: center;
    }

    @media (max-width: 767px) {
        section h2 {
            font-size: 1em;
            margin: 0;
        }

        #map_buttons {
            position: absolute;
            top: 150px;
            border: 1px solid;
            display: none;
        }
    }

    @media (min-width: 767px) {
        #map_buttons {
            position: absolute;
            top: 200px;
            display: none;
        }
    }
</style>
{% endblock %}

{% block content %}
<div style="height: 20px;"></div>
<section id="services" style="padding: 100px 0px 100px 0px ! important;">
    <div class="container">
        <h2 id="title">Browse Field Trials</h2>


        <p id="description"></p>
        <form id="form" role="form">
            <div class="list_service_table">
                <table id="listTable"></table>
            </div>
        </form>
        <div id="status"></div>
        <div id="output_format_div" style="display:none; float:right;">
            <p>Download job format
                <select id="output_format" onchange="changeDownloadFormat();">

                </select>
            </p>
        </div>
        <div style="clear:both;"></div>

        <div id="result"><img src="{% static 'images/ajax-loader.gif' %}"/></div>

        <div id="map"></div>
        <div id="map_buttons">
            <div class="input-group">
               <span class="input-group-btn" id="locationButton">
                    <button type="button" class="btn btn-default" onclick="update_map_location();">My Location
                    </button>
               </span>
            </div>
        </div>
        <div id="tableWrapper">
            <table id="resultTable"></table>
        </div>

        <!-- Modal -->
        <div class="modal " tabindex="-1" role="dialog" id="plotModal" style="z-index: 999999;">
            <div class="modal-dialog  modal-dialog-centered" role="document">
                <div class="modal-content" style="z-index: 9999999;">
                    <div class="modal-header">
                        <h5 class="modal-title"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body" id="modal-body">

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

       
    </div>
</section>
    
    {% endblock %}

    {% block additional_scripts %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#plots').html('<img src="{% static 'images/ajax-loader.gif' %}"/>');
            window.location.href = root_dir + "fieldtrial/all";
        });

    </script>
    {% endblock %}

fieldtrial/templates/fieldtrial/plot.html
{% extends 'base.html' %}
{% load static %}


{% block all_styles_and_scripts %}
{{ block.super }} 
    <style type="text/css">
        .modal-body {
            height: 250px;
            overflow-y: auto;
        }
    
        @media (min-height: 500px) {
            .modal-body {
                height: 400px;
            }
        }
    
        @media (min-height: 800px) {
            .modal-body {
                height: 600px;
            }
        }
    </style>

{% endblock %}

{% block content %}
<div style="height: 20px;"></div>
 <section id="services" style="padding: 100px 0px 1px 0px ! important;">
    <div class="container">
        <h2 id="title">Field Trial Details</h2>

        <p id="description"><br/>Study: <a href="/fieldtrial/study/{{ plot_id|safe }}" target="_blank">{{ study_name|safe }}</a></p>
        <p><a href="{% url 'downloads:download' filename=plot_id %} ">Download csv file of plot data</a>
            &nbsp;&nbsp;&nbsp;&nbsp;
        <a href="#heatmap">Jump to Interactive heatmap visualisation.</a></p>
        <form id="form" role="form">
            <div class="list_service_table">
                <table id="listTable"></table>
            </div>
        </form>
        <div id="status"></div>
        <div id="output_format_div" style="display:none; float:right;">
            <p>Download job format
                <select id="output_format" onchange="changeDownloadFormat();">

                </select>
            </p>
        </div>
        <div style="clear:both;"></div>

        <div id="result"></div>
        <div class="row" style="border-style: solid;border-width:1px;">
            <div class="col">

                <div class="wrapper1" style="overflow: scroll;height: 20px; ">
                    <div id="upperslider" style="width:100%;"></div>
                </div>
                <div id="plots" style="overflow: scroll;"></div>

	    </div>
	</div>
            
        <div class="row" style="border-style: solid;border-width:1px;">
	    <div class="col">
		    
                <div id="control" style="display: none; margin-left: 20px; padding:5px;">
                    <br>
                    Search:</br>
                    <input type="text" id="searchPlotsInput" onkeyup="filter_plot();" value=""/></br><br/>
                    <!--                        Phenotype:</br>-->
                    <!--                        Height: <input type="text" id="height" value="117.25" disabled="disabled"/></br>-->
                    <!--                        Yield: <input type="text" id="yield" value="8.91292789637138" disabled="disabled"/></br><br/>-->
                    <!--                        GRU Accession: <input type="text" id="gruAccession" value="PW141-41-2-20-Q5B-NDVI-W"-->
                    <!--                                              disabled="disabled"/></br>-->
                    <!--                    <button onclick="filter_plot();">Filter</button>-->
                    <div id="filter_result"></div>

                    <!--                    </br></br></br></br>-->
                    <!--                        <button>Get Data</button>-->
                    </p>
                </div>
            
	    </div>
        </div>

        <!-- Modal -->
<div class="modal" tabindex="-1" role="dialog" id="plotModal" style="z-index: 999999;">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" style="z-index: 9999999;">
            <div class="modal-header">
                <h5 class="modal-title">Plot details</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-body">
                <!-- Modal body content here -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

 </section>
 
 <section id="heatmap">
    <h4 id="title">Interactive heatmap</h4>
    <form action = "">
    <p> Select phenotype:
    <select name="singlePhenotype">
        <option selected="selected" disabled="disabled">Select phenotype</option>
        {% for key, value in dictTraits.items %}
            <option value="{{ key }}">{{ value }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Submit">
    </p>
    </form>

 {% autoescape off %}
 {{ plot_div }}
 {% endautoescape %}


 </section>

{% endblock %}

{% block additional_scripts %}
 
  <script type="text/javascript">
    $(document).ready(function () {
        $('#plots').html('<img src="{% static 'images/ajax-loader.gif' %}"/>');
        LoadTable({{ data|safe }});
    });
  </script>

{% endblock %}

<!--content-->

fieldtrial/templates/fieldtrial/plots.html
{% extends 'base.html' %}
{% load static %}


{% block all_styles_and_scripts %}
{{ block.super }} 
<!-- New script to handle images used  by fieldtrial_map.js in formatPlotModal function-->
<script src="{% static 'fieldtrial/SCRIPTS/carousel.js' %}"></script> 
   <style type="text/css">
    .modal-body {
        height: 250px;
        overflow-y: auto;
    }

    @media (min-height: 500px) {
        .modal-body {
            height: 400px;
        }
    }

    @media (min-height: 800px) {
        .modal-body {
            height: 600px;
        }
    }
    .carousel-button {
        cursor: pointer;
        background-color: transparent;
        border: none;
        font-size: 24px;
        padding: 10px;
        top: 50%; /* Center vertically */
        transform: translateY(-50%); /* Center vertically */
        position: absolute;
    }
    
    .carousel-button.left {
        left: 50px; /* Adjust as necessary */
    }
    
    .carousel-button.right {
        right: 50px; /* Adjust as necessary */
    }
    
    .image-carousel {
        display: flex;
        align-items: center;
        justify-content: center;
        position: relative; /* Required for absolute positioning of children */
    }
    
    .image-carousel .carouselImage {
        width: 300px;  /* Fixed width, adjust as necessary */
        height: auto;  /* Maintain aspect ratio */
        display: block;
    }

    .image-container {
        max-width: 100%;
        text-align: center; 
        position: relative; 
    }
    
    .image-title {
        background-color: #fff;
        color: #000; 
        padding: 5px;
        display: block;
        width: 100%;
        text-align: center;
    }
    
</style>
 
{% endblock %}

{% block content %}
<div style="height: 20px;"></div>
 <section id="services" style="padding: 100px 0px 1px 0px ! important;">
    <div class="container">
        <h2 id="title">Field Trial Details</h2>

        <p id="description"><br/>Study: <a href="/fieldtrial/study/{{ plot_id|safe }}" target="_blank">{{ study_name|safe }}</a></p>
        <p><a href="{% url 'downloads:download' filename=plot_id %} ">Download csv file of plot data</a>
            &nbsp;&nbsp;&nbsp;&nbsp;
        <a href="#heatmap">Jump to Interactive heatmap visualisation.</a></p>
        <form id="form" role="form">
            <div class="list_service_table">
                <table id="listTable"></table>
            </div>
        </form>
        <div id="status"></div>
        <div id="output_format_div" style="display:none; float:right;">
            <p>Download job format
                <select id="output_format" onchange="changeDownloadFormat();">

                </select>
            </p>
        </div>
        <div style="clear:both;"></div>

        <div id="result"></div>
        <div class="row" style="border-style: solid;border-width:1px;">
            <div class="col">

                <div class="wrapper1" style="overflow: scroll;height: 20px; ">
                    <div id="upperslider" style="width:100%;"></div>
                </div>
                <div id="plots" style="overflow: scroll;"></div>

	    </div>
	</div>
            
        <div class="row" style="border-style: solid;border-width:1px;">
	    <div class="col">
		    
                <div id="control" style="display: none; margin-left: 20px; padding:5px;">
                    <br>
                    Search:</br>
                    <input type="text" id="searchPlotsInput" onkeyup="filter_plot();" value=""/></br><br/>
                    <!--                        Phenotype:</br>-->
                    <!--                        Height: <input type="text" id="height" value="117.25" disabled="disabled"/></br>-->
                    <!--                        Yield: <input type="text" id="yield" value="8.91292789637138" disabled="disabled"/></br><br/>-->
                    <!--                        GRU Accession: <input type="text" id="gruAccession" value="PW141-41-2-20-Q5B-NDVI-W"-->
                    <!--                                              disabled="disabled"/></br>-->
                    <!--                    <button onclick="filter_plot();">Filter</button>-->
                    <div id="filter_result"></div>

                    <!--                    </br></br></br></br>-->
                    <!--                        <button>Get Data</button>-->
                    </p>
                </div>
            
	    </div>
        </div>

        <!-- Modal -->
<div class="modal" tabindex="-1" role="dialog" id="plotModal" style="z-index: 999999;">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" style="z-index: 9999999;">
            <div class="modal-header">
                <h5 class="modal-title">Plot details</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-body">
                <!-- Modal body content here -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

 </section>
 
 <section id="heatmap">
    <h4 id="title">Interactive heatmap</h4>
    <form action = "">
    <p> Select phenotype:
    <select name="singlePhenotype">
        <option selected="selected" disabled="disabled">Select phenotype</option>
        {% for key, value in dictTraits.items %}
            <option value="{{ key }}">{{ value }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Submit">
    </p>
    </form>

 {% autoescape off %}
 {{ plot_div }}
 {% endautoescape %}


 </section>

{% endblock %}

{% block additional_scripts %}
  <script type="text/javascript">    
    var images = [
        {% for url in imageUrls %}
            "{{ url }}",
        {% endfor %}
    ];
  </script>

 
  <script type="text/javascript">
    $(document).ready(function () {
        $('#plots').html('<img src="{% static 'images/ajax-loader.gif' %}"/>');
        LoadTable({{ data|safe }});
    });
  </script>

{% endblock %}

<!--content-->